name: Waka Readme

on:
  schedule:
    # Runs every hour @ 45th minute.
    # see https://crontab.guru/
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: True
          SHOW_LINES_OF_CODE: False
          SHOW_PROFILE_VIEWS: True
          SHOW_COMMIT: True
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: True
          SHOW_OS: True
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: True
          SHOW_EDITOR: False
